### ISSUE TITLE
Butterfly Monk destroy not triggering Mend

### ISSUE THREAD

**Issue by newtaj** [danj3000/ashteki#293] opened 2021-03-25 22:25 UTC
Had a game where the Butterfly Monk heal didn't trigger after he blocked my beast mage.

Also a separate issue of when I used Figures in the fog to exhaust his attacking unit it acted like he passed his main action

hope this helps?

-taj brings Saria Guideman to battle
shadowfire brings Rin Northfell to battle
 -taj has connected to the game server
 shadowfire has connected to the game server
-taj has chosen their first five
-taj draws 1 card to their maximum of 5
-taj
good luck
shadowfire has chosen their first five
ROUND 1
Prepare phase
-taj rolls 5 basic dice
shadowfire rolls 4 basic dice
 -taj rolled the most basics so will choose first player
shadowfire
thanks you too
 -taj chooses to go second
-taj has not discarded
shadowfire has not discarded
Playerturns phase
Turn 1 - shadowfire
shadowfire plays Summon Frostback Bear
Turn 1 - -taj
-taj plays Summon Three-Eyed Owl
-taj plays Body Inversion
Turn 2 - shadowfire
shadowfire plays Summon False Demon
Turn 2 - -taj
-taj plays Summon Seaside Raven
Turn 3 - shadowfire
shadowfire plays Summon Butterfly Monk
Turn 3 - -taj
-taj uses Summon Three-Eyed Owl to put Three-Eyed Owl into play
Turn 4 - shadowfire
shadowfire plays Frost Bite
Turn 4 - -taj
-taj uses Three-Eyed Owl to discard 1 cards
shadowfire
hm which card to discard
shadowfire discards Fire Archer
Turn 5 - shadowfire
shadowfire uses Summon False Demon to put False Demon into play
shadowfire uses False Demon to deal 1 damage to a target exhausted unit
shadowfire meditates Rin's Fury to gain a 
shadowfire meditated 1 cards/dice
Turn 5 - -taj
-taj plays Hidden Power to Draw a card and change 5 dice
-taj uses Saria Guideman to draw 1 cards
shadowfire discards Frost Bite from the top of their deck
Turn 6 - shadowfire
 shadowfire attacks Saria Guideman with False Demon
Saria Guideman takes 2 damage
Turn 6 - -taj
shadowfire reveals Fire Archer, Fester, Molten Gold, Mist Typhoon, and Frost Fang
-taj removes Molten Gold from the game
Remaining cards are returned as ordered to the top of the deck
Turn 7 - shadowfire
shadowfire uses Summon Frostback Bear to put Frostback Bear into play
shadowfire uses Rin Northfell to attach Ice Buff to Frostback Bear
Turn 7 - -taj
-taj plays Beast Tamer
-taj meditates Hidden Power to gain a 
-taj meditated 1 cards/dice
Turn 8 - shadowfire
shadowfire uses Summon Butterfly Monk to put Butterfly Monk into play
Turn 8 - -taj
-taj uses Summon Seaside Raven to put Seaside Raven into play
-taj uses Seaside Raven to destroy False Demon
False Demon is destroyed
-taj uses  to lower up to 2 opponent dice
Turn 9 - shadowfire
 shadowfire PASSES their main action
Turn 9 - -taj
 -taj attacks Rin Northfell with Seaside Raven
shadowfire uses Frostback Bear to block against Seaside Raven
shadowfire has chosen defenders
Seaside Raven takes 2 damage
Frostback Bear takes 3 damage
Seaside Raven is destroyed
Turn 10 - shadowfire
 shadowfire PASSES their main action
Turn 10 - -taj
 -taj attacks Rin Northfell with Beast Tamer
shadowfire uses Butterfly Monk to block against Beast Tamer
Butterfly Monk takes 2 damage
Butterfly Monk is destroyed
Turn 11 - shadowfire
shadowfire
hey dude i need to enter manual mode cause it seems like i show had have a monk trigger here and it didn't trigger unless i am missing something here
-taj
You didn't have any PB damage?
-taj
Or wait you should of been able to heal the bear
 -taj is attempting to switch manual mode on
 shadowfire allows enabling manual mode
 -taj switches manual mode on
-taj
good catch
 shadowfire removes a damage from Frostback Bear
 -taj switches manual mode off
shadowfire
thanks need to report that later lets continue
-taj
is it your reacton?
 shadowfire PASSES their main action
Turn 11 - -taj
 -taj PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
-taj keeps 0 dice
shadowfire keeps 0 dice
End of round 1
ROUND 2
Prepare phase
-taj has not discarded
shadowfire has not discarded
Playerturns phase
Turn 1 - -taj
-taj uses Summon Three-Eyed Owl to put Three-Eyed Owl into play
-taj uses Saria Guideman to draw 1 cards
shadowfire discards Frost Bite from the top of their deck
Turn 1 - shadowfire
shadowfire plays Mist Typhoon to deal 1 damage to all opponents units
Three-Eyed Owl is destroyed
shadowfire uses  to deal 1 damage to Three-Eyed Owl
Three-Eyed Owl is destroyed
Turn 2 - -taj
-taj plays Purge
shadowfire
no owls for you
-taj meditates Beast Tamer to gain a 
-taj meditates Strange Copy to gain a 
-taj meditates Hidden Power to gain a 
-taj meditated 3 cards/dice
Turn 2 - shadowfire
shadowfire plays Hammer Knight
shadowfire meditates To Shadows to gain a 
shadowfire meditates Hammer Knight to gain a 
shadowfire meditated 2 cards/dice
Turn 3 - -taj
-taj plays Beast Tamer
-taj meditates Summon Three-Eyed Owl to gain a 
-taj meditates Enchanted Violinist to gain a 
-taj meditated 2 cards/dice
Turn 3 - shadowfire
 shadowfire attacks Beast Tamer with Hammer Knight
-taj uses Saria Guideman to guard
-taj plays Redirect to redirect the damage
Beast Tamer takes 2 damage
Beast Tamer is destroyed
shadowfire uses Hammer Knight to deal 1 damage to Beast Tamer
shadowfire
i am going to refresh but it looks like the beast tamer that should be destroyed is there for me
 shadowfire has disconnected. The game will wait up to 30 seconds for them to reconnect
 shadowfire has reconnected
 shadowfire has connected to the game server
 -taj is attempting to switch manual mode on
 shadowfire allows enabling manual mode
 -taj switches manual mode on
 -taj has disconnected. The game will wait up to 30 seconds for them to reconnect
 -taj has reconnected
 -taj has connected to the game server
 -taj switches manual mode off
-taj
??
-taj
wseir
-taj
weird
shadowfire meditates To Shadows to gain a 
shadowfire meditated 1 cards/dice
Turn 4 - -taj
-taj attaches  to Frostback Bear
 -taj attacks Rin Northfell with Beast Tamer
shadowfire uses Frostback Bear to block against Beast Tamer
Frostback Bear takes 2 damage
Frostback Bear is destroyed
Turn 4 - shadowfire
 NIUMath has joined the game as a spectator
shadowfire plays Fester to destroy Beast Tamer
Beast Tamer is destroyed
Turn 5 - -taj
 -taj PASSES their main action
Turn 5 - shadowfire
shadowfire uses Summon Frostback Bear to put Frostback Bear into play
shadowfire uses Rin Northfell to attach Ice Buff to Frostback Bear
Turn 6 - -taj
-taj uses Summon Seaside Raven to put Seaside Raven into play
-taj meditates Seeds Of Aggression to gain a 
-taj meditated 1 cards/dice
Turn 6 - shadowfire
-taj plays Figures In The Fog to exhausts Frostback Bear
shadowfire
good play
-taj
thx
 shadowfire PASSES their main action
Turn 7 - -taj
 -taj attacks Rin Northfell with Seaside Raven
Rin Northfell takes 3 damage
Turn 7 - shadowfire
shadowfire
k that was weird i attack but it said that i did nothing for my main action there
-taj
good point I'll try to get him this chat log and point out those things
shadowfire uses Summon Butterfly Monk to put Butterfly Monk into play
Turn 8 - -taj
 -taj PASSES their main action
Turn 8 - shadowfire
shadowfire
yea please do cause i am not sure on how to do that thanks
 shadowfire attacks Saria Guideman with Butterfly Monk
Saria Guideman takes 1 damage
Turn 9 - -taj
-taj
there is a programmer site called github that has a way to report issues, I think it's linked in the about as an FYI
 -taj PASSES their main action
Turn 9 - shadowfire
 shadowfire PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
shadowfire keeps 0 dice
-taj keeps 0 dice
End of round 2
ROUND 3
Prepare phase
-taj has not discarded
shadowfire has discarded 1 cards from hand
Playerturns phase
Turn 1 - shadowfire
 shadowfire attacks Saria Guideman with Hammer Knight
-taj has chosen defenders
Saria Guideman takes 3 damage
-taj plays Sympathy Pain to deal 2 damage to oppponents unit or phoenixborn
Turn 1 - -taj
-taj plays Rose Fire Dancer
-taj uses Rose Fire Dancer to place 1 exhaustion tokens on Butterfly Monk
Turn 2 - shadowfire
shadowfire uses Summon False Demon to put False Demon into play
shadowfire uses False Demon to deal 1 damage to a target exhausted unit
Rose Fire Dancer is destroyed
Turn 2 - -taj
 -taj attacks Rin Northfell with Seaside Raven
shadowfire uses Frostback Bear to block against Seaside Raven
shadowfire has chosen defenders
shadowfire plays Rin's Fury
Seaside Raven is destroyed
-taj meditates Strange Copy to gain a 
-taj meditated 1 cards/dice
Turn 3 - shadowfire
-taj
good one theere
shadowfire
yea not sure if you are playing any refreshing cards so didn't want to take a chance there
 shadowfire attacks Saria Guideman with False Demon
Saria Guideman takes 2 damage
Turn 3 - -taj
-taj
I have a seeds of agession that I would of used to kill it and your knight
-taj plays Seal to exhausts Summon Frostback Bear
-taj uses Saria Guideman to draw 1 cards
shadowfire discards Rin's Fury from the top of their deck
Turn 4 - shadowfire
shadowfire
so good thing that i did that would had been bad for me
shadowfire plays Fire Archer
shadowfire uses Fire Archer to deal 1 damage to a target phoenixborn
Turn 4 - -taj
-taj uses Summon Seaside Raven to put Seaside Raven into play
-taj uses Seaside Raven to destroy Fire Archer
Fire Archer is destroyed
Turn 5 - shadowfire
shadowfire plays Frost Fang
shadowfire plays Root Armor attaching it to False Demon
Turn 5 - -taj
 -taj attacks Rin Northfell with Seaside Raven
shadowfire uses Frost Fang to block against Seaside Raven
Frost Fang takes 2 damage
Frost Fang is destroyed
-taj meditates Change Psyche to gain a 
-taj meditated 1 cards/dice
Turn 6 - shadowfire
shadowfire
quick question unless i am miss remembering does it frost fang have 3 attack so should have the raven been destroy there unless i am missing something? it is not easy for me to see the cards during the game
-taj
has an ability called quick strike, I'll let you undo the block if you'd like?
shadowfire plays Fire Archer
shadowfire uses Fire Archer to deal 1 damage to a target phoenixborn
shadowfire
totally forgot about that ability that make sense
-taj
it only works when the unit is attacking
shadowfire
i would had still block there anyway
Turn 6 - -taj
-taj meditates Rose Fire Dancer to gain a 
-taj meditated 1 cards/dice
-taj plays Seeds Of Aggression to deal 3 damage to Frostback Bear
Frostback Bear is destroyed
Seaside Raven is destroyed
Turn 7 - shadowfire
 shadowfire attacks Saria Guideman with Fire Archer
Saria Guideman takes 1 damage
Turn 7 - -taj
 -taj PASSES their main action
Turn 8 - shadowfire
shadowfire uses Frost Bite to deal 1 damage to Saria Guideman
Turn 8 - -taj
 -taj PASSES their main action
Turn 9 - shadowfire
 shadowfire PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
shadowfire keeps 0 dice
-taj keeps 0 dice
End of round 3
ROUND 4
Prepare phase
-taj has not discarded
shadowfire has not discarded
Playerturns phase
Turn 1 - -taj
-taj uses Summon Seaside Raven to put Seaside Raven into play
-taj uses Seaside Raven to destroy Fire Archer
Fire Archer is destroyed
-taj meditates Purge to gain a 
-taj meditated 1 cards/dice
Turn 2 - shadowfire
 shadowfire attacks Saria Guideman with False Demon, Butterfly Monk, and Hammer Knight
-taj has chosen defenders
Saria Guideman takes 3 damage
-taj plays Sympathy Pain to deal 2 damage to oppponents unit or phoenixborn
Saria Guideman takes 1 damage
Saria Guideman takes 2 damage
Turn 2 - -taj
-taj plays Summon Three-Eyed Owl
Turn 3 - shadowfire
shadowfire plays Molten Gold to place 3 damage on Saria Guideman
 shadowfire has won the game
-taj
gg
shadowfire
good game now if you could send this chat log to dijon so he can look at the bugs that happened in this game
-taj
yeah thanks for the reminder I forget easily will do

**Comment by danj3000** [comment] 2021-03-27 18:12
These missing destroy triggers are doing my head in - there's no good reason why butterfly monk wouldn't trigger :-/ I have tests all over that, and it all passes. So it must be something odd....
It's good to have the full transcript, but there's nothing obvious...

FiguresInTheFog at least makes sense - it interrupts the attack before the main action cost is spent and exhausts the only attacker - the attack fizzles and the cost is not spent. This I can fix!

**Comment by danj3000** [comment] 2021-04-14 15:01
Closing this. I've added additional test for all edge cases I can think of, but unable to reproduce. 
If this happens again I will reopen.

**Closed by danj3000** 2021-04-14 15:01 UTC
Labels: bug
