### ISSUE TITLE
Gameplay bug: Close Combat did not exhaust or wound my unit

### ISSUE THREAD

**Issue by onecrayon** [danj3000/ashteki#195] opened 2021-02-06 06:27 UTC
I had a Silver Snake in play with an unspeakable number of Status tokens on it and a Root Armor attached. I played Close Combat, targeting the Snake, and dealt **[[redacted]]** damage to his Iron Worker. I was not prompted to either place an exhaustion or a wound, and neither was automatically applied.

Follow-up to this: the instructions for Close Combat are incredibly unclear. The first instruction was something like "select card" with no indication why I should do so. It would be nice if it were something like "select card to deal damage with" => "select card to be dealt damage to" => "pick your poison"

Here's the relevant snippet from the game log along with a little bit of context around it, if it's helpful:

```
Turn 1 - Skaak
Skaak uses  to lower up to 2 opponent dice
Skaak uses Empower to place 1 status on Silver Snake
Skaak uses Silver Snake to gain 1 status token from consume
4649matt uses Chant of Revenge to place 1 status on Chant of Revenge
4649matt uses Chant of Revenge to place 1 status on Chant of Revenge
Turn 1 - 4649matt
4649matt uses Chant of Revenge to deal 1 damage to Maeoni Viper
4649matt plays Iron Worker
Turn 1 - Skaak
Skaak plays Close Combat to deal 18 damage to Iron Worker
Skaak uses Silver Snake to gain 1 status token from consume
Skaak plays Root Armor attaching it to Gilder
```

**Comment by danj3000** [comment] 2021-02-07 10:00
I wrote a test, but could not reproduce the problem. However, it looks like there's a missing reaction entry from chant of revenge - the one that has just been used should have triggered a status token.

SO, I think this may be linked to the problem behind #196 and trigger resolution - assuming Matt clicked something that stopped the resolution chain.

Anyway, I have updated the close combat messaging, and set the chant to auto-resolve without player interaction. I will close this and track the rest as part of #196

**Closed by danj3000** 2021-02-07 10:00 UTC
